# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
{ lib, pkgs, modulesPath, config, chaotic, ... }: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    #     (inputs.nixos-hardware.nixosModules.lenovo-thinkpad-t495)
    #     (../../nixconfig/mediakeys.nix)
  ];

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "24.11"; # Did you read the comment?

  # fingerprint reader
  # fprintd-enroll
  #   services.fprintd.enable = true;

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  # boot.kernelModules = [ "kvm-amd" ];
  # boot.extraModulePackages = with pkgs.linuxPackages_cachyos; [
  boot.extraModulePackages = with config.boot.kernelPackages;
    [
      hid-ite8291r3 # keyboard backlight driver
      # liquidtux
    ];
  boot.consoleLogLevel = 0;
  #  boot.initrd.verbose = false;

  # hardware.tuxedo-rs = {
  #   enable = true;
  #   tailor-gui.enable = true;
  # };

  # Add kernel parameters to fix AMD suspend/resume issues
  boot.kernelParams = [
    "amd_pmc.enable_stb=1" # Enable system trace buffer for better suspend debugging
    "amdgpu.runpm=0" # Disable runtime power management for amdgpu
    "acpi.ec_no_wakeup=1" # Prevent EC from waking system prematurely
  ];

  # networking = {
  #   # useDHCP = true;
  #   interfaces.eno1 = {
  #     useDHCP = false;
  #     ipv4.addresses = [{
  #       address = "192.168.178.2";
  #       prefixLength = 24;
  #     }];
  #   };
  # };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ac6b549c-692f-4cf0-a1b5-caf81f663de2";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-5aaa0ace-fb00-41a0-b417-bdca099d72f9" = {
    device = "/dev/disk/by-uuid/5aaa0ace-fb00-41a0-b417-bdca099d72f9";
    crypttabExtraOpts = [ "tpm2-device=auto" ];
  };

  fileSystems."/boot" = {
    # device = "/dev/disk/by-uuid/B71E-ED70";
    # moved to a dedicated 8G ESP on nvme0n1 (old 512M ESP on nvme1n1p1
    # couldn't fit two kernel/initrd generations at once and kept filling up)
    device = "/dev/disk/by-uuid/5A02-D321";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/fastdata" = {
    device = "/dev/disk/by-uuid/012d1181-0dbf-465e-937b-555a611844d8";
    fsType = "btrfs";
    options = [ "noatime" "compress=zstd" "nofail" ];
    neededForBoot = false;
  };

  swapDevices = [ ];

  # services.xserver.videoDrivers = [ "nvidia" "amdgpu" ];
  services.xserver.videoDrivers =
    [ "nvidia" ]; # amdgpu{-pro}, modesetting, radeon ];
  hardware.cpu.amd.updateMicrocode = true;

  # virtualisation.docker.enableNvidia = true; # deprecated
  hardware.nvidia-container-toolkit.enable = true;

  services.hardware.openrgb.enable = true; # keyboard background lightning

  # Allow user to control RGB keyboard backlight via sysfs
  services.udev.extraRules = ''
    # ITE8291R3 keyboard RGB backlight - allow user to write to color and brightness
    # Match LED devices for ITE8291R3 keyboard (vendor:product 048D:6004)
    SUBSYSTEM=="leds", KERNEL=="*kbd_backlight", MODE="0666"
  '';

  hardware.nvidia = {
    # The proprietary (closed) kernel modules are NOT built by chaotic's cache
    # (nyx-cache.chaotic.cx only has nvidia-open for the cachyos kernel), so
    # `open = false` forces a local build of nvidia-kernel-modules against the
    # LLVM/CachyOS kernel -- which fails the `allowedReferences = [ ]` check in
    # nixpkgs' kernel-modules.nix ("not allowed to refer to
    # /nix/store/...-linux-...-dev"). The open modules are cached and this GPU
    # (10de:2420, GA106M / Ampere) is Turing+, so open is supported.
    open = true;
    modesetting.enable = true;
    nvidiaSettings = true;
    package = pkgs.nvidia_cachyos;
    # package = config.boot.kernelPackages.nvidiaPackages.stable;
    # package = config.boot.kernelPackages.nvidiaPackages.beta;
    # prime = {
    #   offload.enable = true;
    #   offload.enableOffloadCmd = true;
    #   # sync.enable = true;
    #   # reverseSync.enable = true;
    #   # allowExternalGpu = false;
    #   amdgpuBusId = "PCI:5:0:0";
    #   nvidiaBusId = "PCI:1:0:0";
    # };
  };

  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      libva-vdpau-driver
      libvdpau-va-gl
      nvidia-vaapi-driver
      # rocm-opencl-icd
      # rocm-opencl-runtime
      mesa
      vulkan-loader
    ];
  };

  # Virtual display for Sunshine game streaming (see remotecontrol.nix).
  # DP-5 is a real, otherwise-unused output on the Nvidia GPU (nothing is
  # plugged into it). Forcing it "connected" with a synthetic EDID gives
  # Sunshine a capture target that's independent of the internal eDP-1
  # panel, so streaming survives the lid closing / the panel turning off.
  #
  # DP-5, not HDMI-A-1: measured 2026-09-08 by feeding candidate EDIDs
  # through /sys/kernel/debug/dri/0/<connector>/edid_override and reading the
  # drm mode-validation log. On HDMI-A-1, NVKMS caps the pixel clock at
  # 165 MHz -- the single-link TMDS limit, which is what a bare EDID 1.3 with
  # no CTA-861 extension block advertises:
  #     122.50 MHz (1512x982)      -> Probed mode
  #     154.00 MHz (1920x1200 RB)  -> Probed mode
  #     193.25 MHz (1920x1200 CVT) -> Rejected mode ... (BAD)
  #     385.75 MHz (3024x1964 RB)  -> Rejected mode ... (BAD)
  #     507.75 MHz (3024x1964 CVT) -> Rejected mode ... (BAD)
  # The exact same EDID on DP-5 is accepted at 507.75 MHz, because DP mode
  # validation goes against the link rate rather than a TMDS ceiling. Lifting
  # the HDMI ceiling instead would mean hand-crafting a CTA-861 extension
  # block with an HDMI 2.0 HF-VSDB, which `hardware.display` cannot generate.
  # Verified end to end on DP-5: kmsgrab sees a 3024x1964 framebuffer,
  # Sunshine reports "Found connector ID [829]" and validates nvenc against a
  # real KMS capture, and a Moonlight session logs
  # "Video stream is 3024x1964x60".
  #
  # Modeline is `cvt 3024 1964 60` -- the *physical* pixel resolution of the
  # MacBook Pro 14" that connects with Moonlight (2x its 1512x982 logical
  # resolution). Rationale:
  #   - Moonlight requests a stream resolution independently of the capture
  #     size and Sunshine rescales to it. Verified: with this output at
  #     1512x982, `moonlight stream ... --resolution 3024x1964` still logs
  #     "Video stream is 3024x1964x60" -- i.e. Sunshine upscaled. Any mismatch
  #     between the mode here and the client's physical panel costs sharpness,
  #     either as a host-side upscale or a client-side one.
  #   - So the mode must equal the client's physical pixels: 3024x1964. KWin
  #     then runs DP-5 at scale 2 (done by `laptop-screen off`, see
  #     remotecontrol.nix) for a 1512x982 logical desktop rendered at 2x.
  #   - This only pays off with the internal panel *disabled*. While eDP-1 is
  #     enabled, DP-5 is a replica of it (`replicationSource`), so KWin
  #     renders eDP-1's 2226x1252 logical desktop and rescales it into this
  #     mode -- a 1.36x upscale of the same detail. Run `laptop-screen off`
  #     before streaming.
  #
  # `ratio=16:10` is forced because edid-generator's ratio auto-detection
  # only recognizes 16:10/16:9/4:3/5:4 (EDID 1.3's XY_RATIO field only has
  # 2 bits) and 3024:1964 (~1.54) doesn't exactly match any of them -- 16:10
  # is the closest. Note this also makes the EDID advertise a junk 976x610
  # standard timing: the standard-timing byte is (hactive/8 - 31), and 3024
  # overflows it (347 -> 91 -> 976), then 16:10 gives 610. Harmless as long
  # as the 3024x1964 detailed timing is accepted -- but on HDMI-A-1, where it
  # was not, 976x610 was the *only* surviving mode and became the desktop.
  # https://discourse.nixos.org/t/nixos-sunshine-setup-using-a-virtual-screen/64857
  # https://www.azdanov.dev/articles/2025/how-to-create-a-virtual-display-for-sunshine-on-arch-linux
  hardware.display.edid.modelines."MBP60" =
    "507.75  3024 3264 3592 4160  1964 1967 1977 2035 -hsync +vsync ratio=16:10";
  hardware.display.outputs."DP-5" = {
    edid = "MBP60.bin";
    mode = "e";
  };

  environment.systemPackages = with pkgs; [
    # amdgpu_top
    # nvtopPackages.amd
    nvtopPackages.nvidia
    gpustat
    nvitop
    # RGB keyboard control utility
    (writeShellScriptBin "kbd-rgb" (builtins.readFile ./kbd-rgb.sh))
  ];

  powerManagement.enable = true;

  # Sleep config moved to flake.nix (server mode: all suspend disabled with lib.mkForce)

  # radv is mesa's amd driver and replaces amdvlk/radeon
  # environment.variables.AMD_VULKAN_ICD = "RADV";
  # environment.variables.AMD_VULKAN_ICD = "AMDVLK";

  # networking.interfaces.enp3s0f0.useDHCP = true;
  # networking.interfaces.enp4s0.useDHCP = true;
  # networking.interfaces.wlp1s0.useDHCP = true;
  #networking.wireless.interfaces = ["wlp1s0"];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  #   systemd.services.post-resume-hook = {
  #     enable = true;
  #     description = "Commands to execute after resume";
  #     wantedBy = [ "post-resume.target" ];
  #     after = [ "post-resume.target" ];
  #     script =
  #       "/run/current-system/sw/bin/light -s sysfs/leds/tpacpi::power -S 0";
  #     serviceConfig.Type = "oneshot";
  #   };

}
