# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@lit/reactive-element-1.1.1" = {
      name = "_at_lit_slash_reactive-element";
      packageName = "@lit/reactive-element";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@lit/reactive-element/-/reactive-element-1.1.1.tgz";
        sha512 = "B2JdRMwCGv+VpIRj3CYVQBx3muPDeE8y+HPgWqzrAHsO5/40BpwDFZeplIV790BaTqDVUDvZOKMSbuFM9zWC0w==";
      };
    };
    "@material/animation-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_animation";
      packageName = "@material/animation";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/animation/-/animation-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "GBuR4VmcTQW1D0lPXEosf5Giho72LLbyGIydWGtaEUtLJoive/D9kFkwTN4Fsyt9Kkl7hbhs35vrNe6QkAH4/Q==";
      };
    };
    "@material/base-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_base";
      packageName = "@material/base";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/base/-/base-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "UJKbXwZtkrA3sfQDmj8Zbw1Q3Tqtl6KdfVFws95Yf7TCUgTFzbZI/FSx1w7dVugQPOEnIBuZnzqZam/MtHkx4w==";
      };
    };
    "@material/button-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_button";
      packageName = "@material/button";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/button/-/button-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "IPBAByKpQjrWNVmAWx5VCTCLnOw4ymbLsbHmBkLiDgcLPs1EtwYnKKIwQ+/t3bV02OShUdMiyboL8V/C0gMS1A==";
      };
    };
    "@material/circular-progress-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_circular-progress";
      packageName = "@material/circular-progress";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/circular-progress/-/circular-progress-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "4A+HMgp66b45Fvbcbh9qb1j0vRFjKESbE2fHFkSMMNDPqFiKcvq4tJFBxKG2szYzpAnXdWLYaB+DeQ2+wSu9hg==";
      };
    };
    "@material/density-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_density";
      packageName = "@material/density";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/density/-/density-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "Eh/vZ3vVyqtpylg5Ci33qlgtToS4H1/ppd450Ib3tcdISIoodgijYY0w4XsRvrnZgbI/h/1STFdLxdzS0UNuFw==";
      };
    };
    "@material/dialog-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_dialog";
      packageName = "@material/dialog";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/dialog/-/dialog-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "yiG2nlVKTW0Ro3CF8Z/MVpTwSyG/8Kio3AaTUbeQdbjt5r692s4x5Yhd8m1IjEQKUeulY4CndvIbCUwZ8/G2PA==";
      };
    };
    "@material/dom-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_dom";
      packageName = "@material/dom";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/dom/-/dom-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "aR+rfncF6oi2ivdOlKSJI4UXwNzWV5rXM88MLDoSJF1D7lXxhAKhge+tMUBodWGV/q0+FnXLuVAa0WYTrKjo+A==";
      };
    };
    "@material/drawer-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_drawer";
      packageName = "@material/drawer";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/drawer/-/drawer-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "MXzRGq7NoONgbHa+AhAu4HvOUA9V37nSsY4g4Alita08UqRAvvFFr4K1CF9GI2K9pLCpyQv1UbN0Lw5b78HrVQ==";
      };
    };
    "@material/elevation-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_elevation";
      packageName = "@material/elevation";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/elevation/-/elevation-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "3h+EkR588RMZ5TSNQ4UeXD1FOBnL3ABQix0DQIGwtNJCqSMoPndT/oJEFvwQbTkZNDbFIKN9p1Q7/KuFPVY8Pw==";
      };
    };
    "@material/feature-targeting-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_feature-targeting";
      packageName = "@material/feature-targeting";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/feature-targeting/-/feature-targeting-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "fn7Af3PRyARtNeYqtjxXmE3Y/dCpnpQVWWys57MqiGR/nvc6qpgOfJ6rOdcu/MrOysOE/oebTUDmDnTmwpe9Hw==";
      };
    };
    "@material/floating-label-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_floating-label";
      packageName = "@material/floating-label";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/floating-label/-/floating-label-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "gHZUTTVKnP+Zjz4l9IT/G89NPmypn5FlTGLWKKqXbuQphr37rsKFR3Y80SJxULRyMDnAdKSxuZwiXLFKQz9KlA==";
      };
    };
    "@material/focus-ring-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_focus-ring";
      packageName = "@material/focus-ring";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/focus-ring/-/focus-ring-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "exPX5VrjQimipBwgcFDGRiEE783sOBgpkFui59A6i6iGvS2UrLHlYY2E65fyyyQnD1f/rv4Po1OOnCesE1kulg==";
      };
    };
    "@material/form-field-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_form-field";
      packageName = "@material/form-field";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/form-field/-/form-field-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "h9jFm9f5WeMHJWGpQsZ9sPrERLGcDQdW8uvbHAHZ/zN35Mqj43s8+alXROiibx+m1oHLvf2Z01pPWtFSXLYzxA==";
      };
    };
    "@material/icon-button-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_icon-button";
      packageName = "@material/icon-button";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/icon-button/-/icon-button-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "BFdj3CP0JXHC/F2bDmpmzWhum4fkzIDgCCavvnpE/KcCbr0AaoSULRde+LtqvbdLIYW20cXhvjinIOlRhSOshA==";
      };
    };
    "@material/line-ripple-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_line-ripple";
      packageName = "@material/line-ripple";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/line-ripple/-/line-ripple-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "k8f8uuDwnSqZZ98CzbYtQVtxlp1ryUup9nd2uobo3kiqQNlQfXdGkVjuCXcla0OPiKFizNn7dS6Kl/j6L09XUA==";
      };
    };
    "@material/linear-progress-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_linear-progress";
      packageName = "@material/linear-progress";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/linear-progress/-/linear-progress-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "QqkDBcqX7TMt3zQn51LgS7K0y13rJ4ppMQL1f2uYBhDOov8nqndlaXw456KYE9RhU39JrLzVQlaAbU3eecVb/Q==";
      };
    };
    "@material/list-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_list";
      packageName = "@material/list";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/list/-/list-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "mkMpltSKAYLBtFnTTCk/mQIDzwxF/VLh1gh59ehOtmRXt7FvTz83RoAa4tqe53hpVrbX4HoLDBu+vILhq/wkjw==";
      };
    };
    "@material/menu-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_menu";
      packageName = "@material/menu";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/menu/-/menu-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "MmYKVrMIqOtP3TN4vdrrnQrS8P81+tMaA6bKiT9V79R1U6+mKsBYTzaLtLbzyem5vF8O0q7bSwyPwhWPtJr75Q==";
      };
    };
    "@material/menu-surface-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_menu-surface";
      packageName = "@material/menu-surface";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/menu-surface/-/menu-surface-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "IQWb/n15FpLnn+kHp0EqzLE+UoWSPumq3eze2QifiowvGb37bNFR9oSe7CaOzPMrHdkrZ5SBWnDU41wPZN5kOg==";
      };
    };
    "@material/mwc-base-0.27.0" = {
      name = "_at_material_slash_mwc-base";
      packageName = "@material/mwc-base";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-base/-/mwc-base-0.27.0.tgz";
        sha512 = "oCWWtjbyQ52AaUbzINLGBKScIPyqhps2Y7c8t6Gu6fcFeDxhKXMV1Cqvtj/OMhtAt53XjHfD2XruWwYv3cYYUA==";
      };
    };
    "@material/mwc-button-0.27.0" = {
      name = "_at_material_slash_mwc-button";
      packageName = "@material/mwc-button";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-button/-/mwc-button-0.27.0.tgz";
        sha512 = "t5m2zfE93RNKHMjdsU67X6csFzuSG08VJKKvXVQ+BriGE3xBgzY5nZdmZXomFpaWjDENPAlyS4ppCFm6o+DILw==";
      };
    };
    "@material/mwc-checkbox-0.27.0" = {
      name = "_at_material_slash_mwc-checkbox";
      packageName = "@material/mwc-checkbox";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-checkbox/-/mwc-checkbox-0.27.0.tgz";
        sha512 = "EY0iYZLwo8qaqMwR5da4fdn0xI0BZNAvKTcwoubYWpDDHlGxDcqwvjp/40ChGo3Q/zv8/4/A0Qp7cwapI82EkA==";
      };
    };
    "@material/mwc-circular-progress-0.27.0" = {
      name = "_at_material_slash_mwc-circular-progress";
      packageName = "@material/mwc-circular-progress";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-circular-progress/-/mwc-circular-progress-0.27.0.tgz";
        sha512 = "7DkqMb5pUrHfLus5EZ7IT2HUMoE+uPpjGzu3MnDpIzDlfYo6I8p+ifWtEytI0NtXdY5UmITNuCv0RC77mhJrgQ==";
      };
    };
    "@material/mwc-dialog-0.27.0" = {
      name = "_at_material_slash_mwc-dialog";
      packageName = "@material/mwc-dialog";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-dialog/-/mwc-dialog-0.27.0.tgz";
        sha512 = "rkOEmCroVs0wBQbj87vH79SvSHHZ61QRCTUYsU2rHGZCvdzlmvHjWdoyKjJER6WwwM3rrT8xthfecmjICI28CA==";
      };
    };
    "@material/mwc-drawer-0.27.0" = {
      name = "_at_material_slash_mwc-drawer";
      packageName = "@material/mwc-drawer";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-drawer/-/mwc-drawer-0.27.0.tgz";
        sha512 = "dy/uwt+aI5aiUDqFcT6Z4GhGmLZR7fu3HMkfqtQDwoJShxnf5hHwk18fiD1VHHCDf9CZ5wjl7ug4fjpcs9r18A==";
      };
    };
    "@material/mwc-fab-0.27.0" = {
      name = "_at_material_slash_mwc-fab";
      packageName = "@material/mwc-fab";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-fab/-/mwc-fab-0.27.0.tgz";
        sha512 = "7XUxeO14etuXe0FQdB1Y6bg8TilbQKX/NGi9b0O6D0hkcY3Y0Vk2xyoAvQArbHRz3hGfiH1cS7FaJGRSilWcjg==";
      };
    };
    "@material/mwc-floating-label-0.27.0" = {
      name = "_at_material_slash_mwc-floating-label";
      packageName = "@material/mwc-floating-label";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-floating-label/-/mwc-floating-label-0.27.0.tgz";
        sha512 = "uLleloTxQ6dDShcZzqgqfC8otQY8DtGMO9HFQbAEncoFAWpAehcEonsuT/IUhMORN+c5un0P5WXwcZsInJb7og==";
      };
    };
    "@material/mwc-formfield-0.27.0" = {
      name = "_at_material_slash_mwc-formfield";
      packageName = "@material/mwc-formfield";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-formfield/-/mwc-formfield-0.27.0.tgz";
        sha512 = "XGZtC1MTyGQ8b2osnaygGzS3qe2QvlWfXZepcFs9i6MW+b6VimQQ4c/KsKIF7dHmeY6N0o4k9pAZ086EGesXOQ==";
      };
    };
    "@material/mwc-icon-0.27.0" = {
      name = "_at_material_slash_mwc-icon";
      packageName = "@material/mwc-icon";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-icon/-/mwc-icon-0.27.0.tgz";
        sha512 = "Sul44I37M9Ewynn0A9DjkEBrmll2VtNbth6Pxj7I1A/EAwEfaCrPvryyGqfIu1T2hTsRcaojzQx6QjF+B5QW9A==";
      };
    };
    "@material/mwc-icon-button-0.27.0" = {
      name = "_at_material_slash_mwc-icon-button";
      packageName = "@material/mwc-icon-button";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-icon-button/-/mwc-icon-button-0.27.0.tgz";
        sha512 = "wReiPa1UkLaCSPtpkAs1OGKEBtvqPnz9kzuY+RvN5ZQnpo3Uh7n3plHV4y/stsUBfrWtBCcOgYnCdNRaR/r2nQ==";
      };
    };
    "@material/mwc-line-ripple-0.27.0" = {
      name = "_at_material_slash_mwc-line-ripple";
      packageName = "@material/mwc-line-ripple";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-line-ripple/-/mwc-line-ripple-0.27.0.tgz";
        sha512 = "n9Xpt5g3RJEl9rvk14OP6dUNJUtsJA46beTQiep7ppO7IPVFLC1v/5sPpUzfNPUBsclSPxdBuNlCxsgcIYueUw==";
      };
    };
    "@material/mwc-linear-progress-0.27.0" = {
      name = "_at_material_slash_mwc-linear-progress";
      packageName = "@material/mwc-linear-progress";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-linear-progress/-/mwc-linear-progress-0.27.0.tgz";
        sha512 = "kpWVLHPb7RzHU70Dq9bl1lBv05S49rQkyfFoL3PU5tEZHozT8IPQjdBLqAqd7H10cfLVjO7oIB+mVmvnFV+UsQ==";
      };
    };
    "@material/mwc-list-0.27.0" = {
      name = "_at_material_slash_mwc-list";
      packageName = "@material/mwc-list";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-list/-/mwc-list-0.27.0.tgz";
        sha512 = "oAhNQsBuAOgF3ENOIY8PeWjXsl35HoYaUkl0ixBQk8jJP2HIEf+MdbS5688y/UXxFbSjr0m//LfwR5gauEashg==";
      };
    };
    "@material/mwc-menu-0.27.0" = {
      name = "_at_material_slash_mwc-menu";
      packageName = "@material/mwc-menu";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-menu/-/mwc-menu-0.27.0.tgz";
        sha512 = "K+L/t267ZGrlhjK/iSKUVZQKRMkWELArKVglfS5of93ALP4in0RGnj1sOG2u3IFI2F/mEZxRi+wr7HgNxpe0wA==";
      };
    };
    "@material/mwc-notched-outline-0.27.0" = {
      name = "_at_material_slash_mwc-notched-outline";
      packageName = "@material/mwc-notched-outline";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-notched-outline/-/mwc-notched-outline-0.27.0.tgz";
        sha512 = "IlqfQVaEd1RAHqhOG0Xk5JhTDgBe/P9og0pnACglK6bPE0vUhYKwibJiHcr4ACTPtGWHO9o92aktR+7AIEAKtQ==";
      };
    };
    "@material/mwc-radio-0.27.0" = {
      name = "_at_material_slash_mwc-radio";
      packageName = "@material/mwc-radio";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-radio/-/mwc-radio-0.27.0.tgz";
        sha512 = "+rSO9a373BgyMgQOM0Z8vVkuieobBylPJ8qpltytM+yGPj8+n+MtwRZyg+ry3WwEjYYDMP6GxZPHwLgWs6lMpQ==";
      };
    };
    "@material/mwc-ripple-0.27.0" = {
      name = "_at_material_slash_mwc-ripple";
      packageName = "@material/mwc-ripple";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-ripple/-/mwc-ripple-0.27.0.tgz";
        sha512 = "by0O8d8g3Rd96/sUB8hxy6MrDx1QTstqOsA64vqypWd526hMTBGRik08jTNap5sVIyrN9Vq17jb4NJLWQLnNHQ==";
      };
    };
    "@material/mwc-select-0.27.0" = {
      name = "_at_material_slash_mwc-select";
      packageName = "@material/mwc-select";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-select/-/mwc-select-0.27.0.tgz";
        sha512 = "LTr2nl7gAYq8ung4eWfUz24mey4/K9vAlqJBo/uu6w0122C9X64szBS9kHAb87aD1oxLkxAJCDuv/wwlXV1i2w==";
      };
    };
    "@material/mwc-slider-0.27.0" = {
      name = "_at_material_slash_mwc-slider";
      packageName = "@material/mwc-slider";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-slider/-/mwc-slider-0.27.0.tgz";
        sha512 = "lYkxu1vKisV912dkmetkqs/YlS24fULGqKyxPGKC8zlmdN10ZsvpmC6CRIhtHoJeST0JAKunKWdEswTW3pTPaA==";
      };
    };
    "@material/mwc-snackbar-0.27.0" = {
      name = "_at_material_slash_mwc-snackbar";
      packageName = "@material/mwc-snackbar";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-snackbar/-/mwc-snackbar-0.27.0.tgz";
        sha512 = "D9xhae4MiUwhHJxXaNzucmOutXVS/02CVnuCpzV2uDCLnY4oTaiZNDa+YBxheZnNKTTSm5yrshOnsRIQO6hgPw==";
      };
    };
    "@material/mwc-switch-0.27.0" = {
      name = "_at_material_slash_mwc-switch";
      packageName = "@material/mwc-switch";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-switch/-/mwc-switch-0.27.0.tgz";
        sha512 = "MKKjm42f8YyHN1HmvfgppgTPJUxulcmOqND5R7zI/kB38vFcWDxEhnpdUYr2kEsFtebpYNSF0j6FXcKV/W+fJw==";
      };
    };
    "@material/mwc-tab-0.27.0" = {
      name = "_at_material_slash_mwc-tab";
      packageName = "@material/mwc-tab";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-tab/-/mwc-tab-0.27.0.tgz";
        sha512 = "BhX6hZYjPL+d3Gcl6rVHNPiEAudgMHA+7mHo2keqbIiFRLKa2CU+omHZO/82+EBan/TPL6ZK39Oki8aIaAJcRQ==";
      };
    };
    "@material/mwc-tab-bar-0.27.0" = {
      name = "_at_material_slash_mwc-tab-bar";
      packageName = "@material/mwc-tab-bar";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-tab-bar/-/mwc-tab-bar-0.27.0.tgz";
        sha512 = "CqRZ38m8kOfSJo87Ek61eubO8AGR10Dp12c3pCyyy6mtK/0FSY+rfcmnMPxEzkxREqUnQPgw9lhqmGZXBSqzZQ==";
      };
    };
    "@material/mwc-tab-indicator-0.27.0" = {
      name = "_at_material_slash_mwc-tab-indicator";
      packageName = "@material/mwc-tab-indicator";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-tab-indicator/-/mwc-tab-indicator-0.27.0.tgz";
        sha512 = "bdE5mYP2ze/8d8cGTTJUS0+ByzEK5tmWsXfphFr/Dyy9b+gOnIOt1iX8tmKTOpbYKsV43LxtSkumhTTPDXEJLg==";
      };
    };
    "@material/mwc-tab-scroller-0.27.0" = {
      name = "_at_material_slash_mwc-tab-scroller";
      packageName = "@material/mwc-tab-scroller";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-tab-scroller/-/mwc-tab-scroller-0.27.0.tgz";
        sha512 = "WL/CYVx1cHjC1a/STIB/BaBfxGz3Rz4szNNX35FkYzm6GSGxUNkXZfKOAK7R8RdZOAETa8Gy5tTEhKZKKJ/aUA==";
      };
    };
    "@material/mwc-textarea-0.27.0" = {
      name = "_at_material_slash_mwc-textarea";
      packageName = "@material/mwc-textarea";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-textarea/-/mwc-textarea-0.27.0.tgz";
        sha512 = "4srpZ+//Ce0A+OZ3NVjv/YIDDxnpStmpZwTGICMCGsQzQqHyGDX17NhL5mGP8xGguma/ZIgcY6gm7+UQWaTx4g==";
      };
    };
    "@material/mwc-textfield-0.27.0" = {
      name = "_at_material_slash_mwc-textfield";
      packageName = "@material/mwc-textfield";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-textfield/-/mwc-textfield-0.27.0.tgz";
        sha512 = "4/OEeEVAWWQ1DzpjeMLYLsa9HMlifOPjAvi0681Yj1g/RYJs5ONZS80HZ8HOT+efAOlZDugshgM4gdNS3I0XFQ==";
      };
    };
    "@material/mwc-top-app-bar-0.27.0" = {
      name = "_at_material_slash_mwc-top-app-bar";
      packageName = "@material/mwc-top-app-bar";
      version = "0.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/mwc-top-app-bar/-/mwc-top-app-bar-0.27.0.tgz";
        sha512 = "vHn10exeDhUVFpo4TgBsS8pta4AxZtjuuxrYFHMYxceGifEATvGbYoPyw1x7cCMcXMMIITElgfCURAbCmn3BgA==";
      };
    };
    "@material/notched-outline-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_notched-outline";
      packageName = "@material/notched-outline";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/notched-outline/-/notched-outline-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "3ByiPOC/wWQmFKfgJS98kb5/6v92n7uIfJ6v6sryKJlJCJn39qfpGcCM5RpRIws1RET1s1zBJT2JDwYeu/hM5A==";
      };
    };
    "@material/progress-indicator-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_progress-indicator";
      packageName = "@material/progress-indicator";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/progress-indicator/-/progress-indicator-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "vW0oZK70QOpAarip95ueCQ/I3kBClcWjxsc0F0QjkqT76DOVXpjnZ4XoRRyq9eMpwLqlKLTecrsSNpmqwwF1Dg==";
      };
    };
    "@material/radio-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_radio";
      packageName = "@material/radio";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/radio/-/radio-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "V/AgWEOuHFoh9d4Gq1rqBZnKSGtMLQNh23Bwrv0c1FhPqFvUpwt9jR3SVwhJk5gvQQWGy9p3iiGc9QCJ+0+P8Q==";
      };
    };
    "@material/ripple-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_ripple";
      packageName = "@material/ripple";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/ripple/-/ripple-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "6g2G62vd8DsMuIUSXlRrzb98qkZ4o8ZREknNwNP2zaLQEOkJ//4j9HaqDt98/3LIjUTY9UIVFTQENiMmlwKHYQ==";
      };
    };
    "@material/rtl-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_rtl";
      packageName = "@material/rtl";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/rtl/-/rtl-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "f08LT0HSa0WYU+4Jz/tbm1TQ9Fcf2k+H6dPPYv0J1sZmX6hMgCEmNiUdUFLQFvszoXx2XrRi1/hIFjbz2e69Yg==";
      };
    };
    "@material/select-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_select";
      packageName = "@material/select";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/select/-/select-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "fAiTaHZ1PIEmCUbufS+IZvsWO0hDxtbU8rOsbmSu1oupAboP7jSgOVgcCGdT9KY5WacrniIIMO6jZjhnvrC0Lg==";
      };
    };
    "@material/shape-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_shape";
      packageName = "@material/shape";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/shape/-/shape-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "RyjInLCNe+nI/ulKea0ZLHphXQDiDqYazS25SRn18g8Hoa5qGNaY5oOBncDXUYn3jm5oI5kFc9oif//kulkbjg==";
      };
    };
    "@material/slider-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_slider";
      packageName = "@material/slider";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/slider/-/slider-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "vsKgzDrIZh098zy3+zuxZaBvlbfVCbr/4H5a9cPhnUN947+RgqGWnPYgTozVQbFvFfN2pDi1aHOssUaayOUKvw==";
      };
    };
    "@material/snackbar-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_snackbar";
      packageName = "@material/snackbar";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/snackbar/-/snackbar-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "E/i+o7Q8Jp4UW7UBTslqlFeSxgyU7XE86CoYuq2g+ySSWTt8b16ug8EJTQvuk4DRdDO3tjQN1sN0R77Av6txSw==";
      };
    };
    "@material/switch-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_switch";
      packageName = "@material/switch";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/switch/-/switch-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "hL7lOF8tgYaS1Spce6zlxfveoqUlqDTW+vv+R7TIHwzLD5HJCdhTiotXshOKCZLoSi7Ljx7JpCdvNqGlv4rpIw==";
      };
    };
    "@material/tab-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_tab";
      packageName = "@material/tab";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/tab/-/tab-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "Vmjugm9TBF906pNE2kORSDcMUYXQXV+uspFdbyoSH3hVOTjX+Bw+ODL9agW+pDsJRqGMLO/BAoZ0YQDCrCNX/A==";
      };
    };
    "@material/tab-bar-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_tab-bar";
      packageName = "@material/tab-bar";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/tab-bar/-/tab-bar-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "qLTxl0SWwSpsWBV5o7fMO4HaA3NSCTroM+qkUJYNq7lumMXxax8XP6+GvgbXXfsF1K6VqwSPJHnFt5g1kvtBOA==";
      };
    };
    "@material/tab-indicator-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_tab-indicator";
      packageName = "@material/tab-indicator";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/tab-indicator/-/tab-indicator-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "CMh5MuQamk10oYs0NpQwJ+JLPcY+WftU1b2NpAxbke+6yaV0XrcEkymSfHDkMB5itDvtpXR4fe2Yw9wO8gvcgg==";
      };
    };
    "@material/tab-scroller-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_tab-scroller";
      packageName = "@material/tab-scroller";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/tab-scroller/-/tab-scroller-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "eJJWfNDSdjrRVNHkSecblN26PtM8rTeK2FqcZh3iCYRZ74ywhKmHF+elrM2KRH8ez+u/YcZoQacgS8rX3v6ygw==";
      };
    };
    "@material/textfield-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_textfield";
      packageName = "@material/textfield";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/textfield/-/textfield-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "Pla9Tr94Is18o97E/mqHKdkR24rPES9atGm3BlXrNzyr5tu6+h++RBbxy7V6IExcfl0MX+v9Gyqz7sPZzFtwMA==";
      };
    };
    "@material/theme-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_theme";
      packageName = "@material/theme";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/theme/-/theme-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "S06XAevDCDWMe+GgsEpITMS07imUidzadNaTbJsqssFajBLr53QWVZsG84BpjXKXoYvyEJvb0hX5U0lq6ip9UQ==";
      };
    };
    "@material/tokens-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_tokens";
      packageName = "@material/tokens";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/tokens/-/tokens-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "myHFB7vac8zErA3qgkqmV+kpE+i9JEwc/6Yf0MOumDSpylJGw28QikpNC6eAVBK2EmPQTaFn20mqUxyud8dGqw==";
      };
    };
    "@material/top-app-bar-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_top-app-bar";
      packageName = "@material/top-app-bar";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/top-app-bar/-/top-app-bar-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "9vPLLxUbNrWNCPGHoIeIUtyXWQUNh+yQwnkTYVkVAVEb1CsWb2D+/NefytfvyFtXWBFQLybAeG5RH0ZqdcgQBQ==";
      };
    };
    "@material/touch-target-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_touch-target";
      packageName = "@material/touch-target";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/touch-target/-/touch-target-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "d83e5vbqoLyL542yOTTp4TLVltddWiqbI/j1w/D9ipE30YKfe2EDN+CNJc32Zufh5IUfK41DsZdrN8fI9cL99A==";
      };
    };
    "@material/typography-14.0.0-canary.53b3cad2f.0" = {
      name = "_at_material_slash_typography";
      packageName = "@material/typography";
      version = "14.0.0-canary.53b3cad2f.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@material/typography/-/typography-14.0.0-canary.53b3cad2f.0.tgz";
        sha512 = "9J0k2fq7uyHsRzRqJDJLGmg3YzRpfRPtFDVeUH/xBcYoqpZE7wYw5Mb7s/l8eP626EtR7HhXhSPjvRTLA6NIJg==";
      };
    };
    "@mdi/js-5.9.55" = {
      name = "_at_mdi_slash_js";
      packageName = "@mdi/js";
      version = "5.9.55";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mdi/js/-/js-5.9.55.tgz";
        sha512 = "BbeHMgeK2/vjdJIRnx12wvQ6s8xAYfvMmEAVsUx9b+7GiQGQ9Za8jpwp17dMKr9CgKRvemlAM4S7S3QOtEbp4A==";
      };
    };
    "@nodelib/fs.scandir-2.1.5" = {
      name = "_at_nodelib_slash_fs.scandir";
      packageName = "@nodelib/fs.scandir";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.scandir/-/fs.scandir-2.1.5.tgz";
        sha512 = "vq24Bq3ym5HEQm2NKCr3yXDwjc7vTsEThRDnkp2DK9p1uqLR+DHurm/NOTo0KG7HYHU7eppKZj3MyqYuMBf62g==";
      };
    };
    "@nodelib/fs.stat-2.0.5" = {
      name = "_at_nodelib_slash_fs.stat";
      packageName = "@nodelib/fs.stat";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.stat/-/fs.stat-2.0.5.tgz";
        sha512 = "RkhPPp2zrqDAQA/2jNhnztcPAlv64XdhIp7a7454A5ovI7Bukxgt7MX7udwAu3zg1DcpPU0rz3VV1SeaqvY4+A==";
      };
    };
    "@nodelib/fs.walk-1.2.8" = {
      name = "_at_nodelib_slash_fs.walk";
      packageName = "@nodelib/fs.walk";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.walk/-/fs.walk-1.2.8.tgz";
        sha512 = "oGB+UxlgWcgQkgwo8GcEGwemoTFt3FIO9ababBmaGwXIoBKZ+GTy0pP185beGg7Llih/NSHSV2XAs1lnznocSg==";
      };
    };
    "@popperjs/core-2.11.7" = {
      name = "_at_popperjs_slash_core";
      packageName = "@popperjs/core";
      version = "2.11.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@popperjs/core/-/core-2.11.7.tgz";
        sha512 = "Cr4OjIkipTtcXKjAsm8agyleBuDHvxzeBoa1v543lbv1YaIwQjESsVcmjiWiPEbC1FIeHOG/Op9kdCmAmiS3Kw==";
      };
    };
    "@types/fs-extra-8.1.2" = {
      name = "_at_types_slash_fs-extra";
      packageName = "@types/fs-extra";
      version = "8.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/fs-extra/-/fs-extra-8.1.2.tgz";
        sha512 = "SvSrYXfWSc7R4eqnOzbQF4TZmfpNSM9FrSWLU3EUnWBuyZqNBOrv1B1JA3byUDPUl9z4Ab3jeZG2eDdySlgNMg==";
      };
    };
    "@types/geojson-7946.0.8" = {
      name = "_at_types_slash_geojson";
      packageName = "@types/geojson";
      version = "7946.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/geojson/-/geojson-7946.0.8.tgz";
        sha512 = "1rkryxURpr6aWP7R786/UQOkJ3PcpQiWkAXBmdWc7ryFWqN6a4xfK7BtjXvFBKO9LjQ+MWQSWxYeZX1OApnArA==";
      };
    };
    "@types/glob-7.1.4" = {
      name = "_at_types_slash_glob";
      packageName = "@types/glob";
      version = "7.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/glob/-/glob-7.1.4.tgz";
        sha512 = "w+LsMxKyYQm347Otw+IfBXOv9UWVjpHpCDdbBMt8Kz/xbvCYNjP+0qPh91Km3iKfSRLBB0P7fAMf0KHrPu+MyA==";
      };
    };
    "@types/leaflet-1.7.5" = {
      name = "_at_types_slash_leaflet";
      packageName = "@types/leaflet";
      version = "1.7.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/leaflet/-/leaflet-1.7.5.tgz";
        sha512 = "+Myo00Yb5OuvUyrH+vUwn9DRgOaBJsF/etIMdMcNhWGBMo58Mo1cxLInvCd0ZpvItju/AeDYFB/Od2pLiHB3VA==";
      };
    };
    "@types/minimatch-3.0.5" = {
      name = "_at_types_slash_minimatch";
      packageName = "@types/minimatch";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/minimatch/-/minimatch-3.0.5.tgz";
        sha512 = "Klz949h02Gz2uZCMGwDUSDS1YBlTdDDgbWHi+81l29tQALUtvz4rAYi5uoVhE5Lagoq6DeqAUlbrHvW/mXDgdQ==";
      };
    };
    "@types/node-16.7.6" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "16.7.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-16.7.6.tgz";
        sha512 = "VESVNFoa/ahYA62xnLBjo5ur6gPsgEE5cNRy8SrdnkZ2nwJSW0kJ4ufbFr2zuU9ALtHM8juY53VcRoTA7htXSg==";
      };
    };
    "@types/trusted-types-2.0.2" = {
      name = "_at_types_slash_trusted-types";
      packageName = "@types/trusted-types";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/trusted-types/-/trusted-types-2.0.2.tgz";
        sha512 = "F5DIZ36YVLE+PN+Zwws4kJogq47hNgX3Nx6WyDJ3kcplxyke3XIzB8uK5n/Lpm1HBsbGzd6nmGehL8cPekP+Tg==";
      };
    };
    "array-union-2.1.0" = {
      name = "array-union";
      packageName = "array-union";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-union/-/array-union-2.1.0.tgz";
        sha512 = "HGyxoOTYUyCM6stUe6EJgnd4EoewAI7zMdfqO+kGjnlZmBDz/cR5pf8r/cR4Wq60sL/p0IkcjUEEPwS3GFrIyw==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "blocking-elements-0.1.1" = {
      name = "blocking-elements";
      packageName = "blocking-elements";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/blocking-elements/-/blocking-elements-0.1.1.tgz";
        sha512 = "/SLWbEzMoVIMZACCyhD/4Ya2M1PWP1qMKuiymowPcI+PdWDARqeARBjhj73kbUBCxEmTZCUu5TAqxtwUO9C1Ig==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "braces-3.0.2" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.2.tgz";
        sha512 = "b8um+L1RzM3WDSzvhm6gIz1yfTbBt6YTlcEKAvsmqCZZFw46z626lVj9j1yEPW33H5H+lBQpZMP1k8l+78Ha0A==";
      };
    };
    "colorette-1.3.0" = {
      name = "colorette";
      packageName = "colorette";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/colorette/-/colorette-1.3.0.tgz";
        sha512 = "ecORCqbSFP7Wm8Y6lyqMJjexBQqXSF7SSeaTyGGphogUjBlFP9m9o08wy86HL2uB7fMTxtOUzLMk7ogKcxMg1w==";
      };
    };
    "commander-7.2.0" = {
      name = "commander";
      packageName = "commander";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-7.2.0.tgz";
        sha512 = "QrWXB+ZQSVPmIWIhtEO9H+gwHaMGYiF5ChvoJ+K9ZGHG/sVsa6yiesAD1GC/x46sET00Xlwo1u49RVVVzvcSkw==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "d3-7.8.2" = {
      name = "d3";
      packageName = "d3";
      version = "7.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3/-/d3-7.8.2.tgz";
        sha512 = "WXty7qOGSHb7HR7CfOzwN1Gw04MUOzN8qh9ZUsvwycIMb4DYMpY9xczZ6jUorGtO6bR9BPMPaueIKwiDxu9uiQ==";
      };
    };
    "d3-array-3.2.2" = {
      name = "d3-array";
      packageName = "d3-array";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-array/-/d3-array-3.2.2.tgz";
        sha512 = "yEEyEAbDrF8C6Ob2myOBLjwBLck1Z89jMGFee0oPsn95GqjerpaOA4ch+vc2l0FNFFwMD5N7OCSEN5eAlsUbgQ==";
      };
    };
    "d3-axis-3.0.0" = {
      name = "d3-axis";
      packageName = "d3-axis";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-axis/-/d3-axis-3.0.0.tgz";
        sha512 = "IH5tgjV4jE/GhHkRV0HiVYPDtvfjHQlQfJHs0usq7M30XcSBvOotpmH1IgkcXsO/5gEQZD43B//fc7SRT5S+xw==";
      };
    };
    "d3-brush-3.0.0" = {
      name = "d3-brush";
      packageName = "d3-brush";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-brush/-/d3-brush-3.0.0.tgz";
        sha512 = "ALnjWlVYkXsVIGlOsuWH1+3udkYFI48Ljihfnh8FZPF2QS9o+PzGLBslO0PjzVoHLZ2KCVgAM8NVkXPJB2aNnQ==";
      };
    };
    "d3-chord-3.0.1" = {
      name = "d3-chord";
      packageName = "d3-chord";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-chord/-/d3-chord-3.0.1.tgz";
        sha512 = "VE5S6TNa+j8msksl7HwjxMHDM2yNK3XCkusIlpX5kwauBfXuyLAtNg9jCp/iHH61tgI4sb6R/EIMWCqEIdjT/g==";
      };
    };
    "d3-color-2.0.0" = {
      name = "d3-color";
      packageName = "d3-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-color/-/d3-color-2.0.0.tgz";
        sha512 = "SPXi0TSKPD4g9tw0NMZFnR95XVgUZiBH+uUTqQuDu1OsE2zomHU7ho0FISciaPvosimixwHFl3WHLGabv6dDgQ==";
      };
    };
    "d3-color-3.1.0" = {
      name = "d3-color";
      packageName = "d3-color";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-color/-/d3-color-3.1.0.tgz";
        sha512 = "zg/chbXyeBtMQ1LbD/WSoW2DpC3I0mpmPdW+ynRTj/x2DAWYrIY7qeZIHidozwV24m4iavr15lNwIwLxRmOxhA==";
      };
    };
    "d3-contour-4.0.2" = {
      name = "d3-contour";
      packageName = "d3-contour";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-contour/-/d3-contour-4.0.2.tgz";
        sha512 = "4EzFTRIikzs47RGmdxbeUvLWtGedDUNkTcmzoeyg4sP/dvCexO47AaQL7VKy/gul85TOxw+IBgA8US2xwbToNA==";
      };
    };
    "d3-delaunay-6.0.2" = {
      name = "d3-delaunay";
      packageName = "d3-delaunay";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-delaunay/-/d3-delaunay-6.0.2.tgz";
        sha512 = "IMLNldruDQScrcfT+MWnazhHbDJhcRJyOEBAJfwQnHle1RPh6WDuLvxNArUju2VSMSUuKlY5BGHRJ2cYyoFLQQ==";
      };
    };
    "d3-dispatch-2.0.0" = {
      name = "d3-dispatch";
      packageName = "d3-dispatch";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-dispatch/-/d3-dispatch-2.0.0.tgz";
        sha512 = "S/m2VsXI7gAti2pBoLClFFTMOO1HTtT0j99AuXLoGFKO6deHDdnv6ZGTxSTTUTgO1zVcv82fCOtDjYK4EECmWA==";
      };
    };
    "d3-dispatch-3.0.1" = {
      name = "d3-dispatch";
      packageName = "d3-dispatch";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-dispatch/-/d3-dispatch-3.0.1.tgz";
        sha512 = "rzUyPU/S7rwUflMyLc1ETDeBj0NRuHKKAcvukozwhshr6g6c5d8zh4c2gQjY2bZ0dXeGLWc1PF174P2tVvKhfg==";
      };
    };
    "d3-drag-2.0.0" = {
      name = "d3-drag";
      packageName = "d3-drag";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-drag/-/d3-drag-2.0.0.tgz";
        sha512 = "g9y9WbMnF5uqB9qKqwIIa/921RYWzlUDv9Jl1/yONQwxbOfszAWTCm8u7HOTgJgRDXiRZN56cHT9pd24dmXs8w==";
      };
    };
    "d3-drag-3.0.0" = {
      name = "d3-drag";
      packageName = "d3-drag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-drag/-/d3-drag-3.0.0.tgz";
        sha512 = "pWbUJLdETVA8lQNJecMxoXfH6x+mO2UQo8rSmZ+QqxcbyA3hfeprFgIT//HW2nlHChWeIIMwS2Fq+gEARkhTkg==";
      };
    };
    "d3-dsv-3.0.1" = {
      name = "d3-dsv";
      packageName = "d3-dsv";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-dsv/-/d3-dsv-3.0.1.tgz";
        sha512 = "UG6OvdI5afDIFP9w4G0mNq50dSOsXHJaRE8arAS5o9ApWnIElp8GZw1Dun8vP8OyHOZ/QJUKUJwxiiCCnUwm+Q==";
      };
    };
    "d3-ease-2.0.0" = {
      name = "d3-ease";
      packageName = "d3-ease";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-ease/-/d3-ease-2.0.0.tgz";
        sha512 = "68/n9JWarxXkOWMshcT5IcjbB+agblQUaIsbnXmrzejn2O82n3p2A9R2zEB9HIEFWKFwPAEDDN8gR0VdSAyyAQ==";
      };
    };
    "d3-ease-3.0.1" = {
      name = "d3-ease";
      packageName = "d3-ease";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-ease/-/d3-ease-3.0.1.tgz";
        sha512 = "wR/XK3D3XcLIZwpbvQwQ5fK+8Ykds1ip7A2Txe0yxncXSdq1L9skcG7blcedkOX+ZcgxGAmLX1FrRGbADwzi0w==";
      };
    };
    "d3-fetch-3.0.1" = {
      name = "d3-fetch";
      packageName = "d3-fetch";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-fetch/-/d3-fetch-3.0.1.tgz";
        sha512 = "kpkQIM20n3oLVBKGg6oHrUchHM3xODkTzjMoj7aWQFq5QEM+R6E4WkzT5+tojDY7yjez8KgCBRoj4aEr99Fdqw==";
      };
    };
    "d3-force-3.0.0" = {
      name = "d3-force";
      packageName = "d3-force";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-force/-/d3-force-3.0.0.tgz";
        sha512 = "zxV/SsA+U4yte8051P4ECydjD/S+qeYtnaIyAs9tgHCqfguma/aAQDjo85A9Z6EKhBirHRJHXIgJUlffT4wdLg==";
      };
    };
    "d3-format-2.0.0" = {
      name = "d3-format";
      packageName = "d3-format";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-format/-/d3-format-2.0.0.tgz";
        sha512 = "Ab3S6XuE/Q+flY96HXT0jOXcM4EAClYFnRGY5zsjRGNy6qCYrQsMffs7cV5Q9xejb35zxW5hf/guKw34kvIKsA==";
      };
    };
    "d3-format-3.1.0" = {
      name = "d3-format";
      packageName = "d3-format";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-format/-/d3-format-3.1.0.tgz";
        sha512 = "YyUI6AEuY/Wpt8KWLgZHsIU86atmikuoOmCfommt0LYHiQSPjvX2AcFc38PX0CBpr2RCyZhjex+NS/LPOv6YqA==";
      };
    };
    "d3-geo-3.1.0" = {
      name = "d3-geo";
      packageName = "d3-geo";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-geo/-/d3-geo-3.1.0.tgz";
        sha512 = "JEo5HxXDdDYXCaWdwLRt79y7giK8SbhZJbFWXqbRTolCHFI5jRqteLzCsq51NKbUoX0PjBVSohxrx+NoOUujYA==";
      };
    };
    "d3-hierarchy-3.1.2" = {
      name = "d3-hierarchy";
      packageName = "d3-hierarchy";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-hierarchy/-/d3-hierarchy-3.1.2.tgz";
        sha512 = "FX/9frcub54beBdugHjDCdikxThEqjnR93Qt7PvQTOHxyiNCAlvMrHhclk3cD5VeAaq9fxmfRp+CnWw9rEMBuA==";
      };
    };
    "d3-interpolate-2.0.1" = {
      name = "d3-interpolate";
      packageName = "d3-interpolate";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-interpolate/-/d3-interpolate-2.0.1.tgz";
        sha512 = "c5UhwwTs/yybcmTpAVqwSFl6vrQ8JZJoT5F7xNFK9pymv5C0Ymcc9/LIJHtYIggg/yS9YHw8i8O8tgb9pupjeQ==";
      };
    };
    "d3-interpolate-3.0.1" = {
      name = "d3-interpolate";
      packageName = "d3-interpolate";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-interpolate/-/d3-interpolate-3.0.1.tgz";
        sha512 = "3bYs1rOD33uo8aqJfKP3JWPAibgw8Zm2+L9vBKEHJ2Rg+viTR7o5Mmv5mZcieN+FRYaAOWX5SJATX6k1PWz72g==";
      };
    };
    "d3-path-2.0.0" = {
      name = "d3-path";
      packageName = "d3-path";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-path/-/d3-path-2.0.0.tgz";
        sha512 = "ZwZQxKhBnv9yHaiWd6ZU4x5BtCQ7pXszEV9CU6kRgwIQVQGLMv1oiL4M+MK/n79sYzsj+gcgpPQSctJUsLN7fA==";
      };
    };
    "d3-path-3.1.0" = {
      name = "d3-path";
      packageName = "d3-path";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-path/-/d3-path-3.1.0.tgz";
        sha512 = "p3KP5HCf/bvjBSSKuXid6Zqijx7wIfNW+J/maPs+iwR35at5JCbLUT0LzF1cnjbCHWhqzQTIN2Jpe8pRebIEFQ==";
      };
    };
    "d3-polygon-3.0.1" = {
      name = "d3-polygon";
      packageName = "d3-polygon";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-polygon/-/d3-polygon-3.0.1.tgz";
        sha512 = "3vbA7vXYwfe1SYhED++fPUQlWSYTTGmFmQiany/gdbiWgU/iEyQzyymwL9SkJjFFuCS4902BSzewVGsHHmHtXg==";
      };
    };
    "d3-quadtree-3.0.1" = {
      name = "d3-quadtree";
      packageName = "d3-quadtree";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-quadtree/-/d3-quadtree-3.0.1.tgz";
        sha512 = "04xDrxQTDTCFwP5H6hRhsRcb9xxv2RzkcsygFzmkSIOJy3PeRJP7sNk3VRIbKXcog561P9oU0/rVH6vDROAgUw==";
      };
    };
    "d3-random-3.0.1" = {
      name = "d3-random";
      packageName = "d3-random";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-random/-/d3-random-3.0.1.tgz";
        sha512 = "FXMe9GfxTxqd5D6jFsQ+DJ8BJS4E/fT5mqqdjovykEB2oFbTMDVdg1MGFxfQW+FBOGoB++k8swBrgwSHT1cUXQ==";
      };
    };
    "d3-scale-4.0.2" = {
      name = "d3-scale";
      packageName = "d3-scale";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-scale/-/d3-scale-4.0.2.tgz";
        sha512 = "GZW464g1SH7ag3Y7hXjf8RoUuAFIqklOAq3MRl4OaWabTFJY9PN/E1YklhXLh+OQ3fM9yS2nOkCoS+WLZ6kvxQ==";
      };
    };
    "d3-scale-chromatic-3.0.0" = {
      name = "d3-scale-chromatic";
      packageName = "d3-scale-chromatic";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-scale-chromatic/-/d3-scale-chromatic-3.0.0.tgz";
        sha512 = "Lx9thtxAKrO2Pq6OO2Ua474opeziKr279P/TKZsMAhYyNDD3EnCffdbgeSYN5O7m2ByQsxtuP2CSDczNUIZ22g==";
      };
    };
    "d3-selection-2.0.0" = {
      name = "d3-selection";
      packageName = "d3-selection";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-selection/-/d3-selection-2.0.0.tgz";
        sha512 = "XoGGqhLUN/W14NmaqcO/bb1nqjDAw5WtSYb2X8wiuQWvSZUsUVYsOSkOybUrNvcBjaywBdYPy03eXHMXjk9nZA==";
      };
    };
    "d3-selection-3.0.0" = {
      name = "d3-selection";
      packageName = "d3-selection";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-selection/-/d3-selection-3.0.0.tgz";
        sha512 = "fmTRWbNMmsmWq6xJV8D19U/gw/bwrHfNXxrIN+HfZgnzqTHp9jOmKMhsTUjXOJnZOdZY9Q28y4yebKzqDKlxlQ==";
      };
    };
    "d3-shape-3.2.0" = {
      name = "d3-shape";
      packageName = "d3-shape";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-shape/-/d3-shape-3.2.0.tgz";
        sha512 = "SaLBuwGm3MOViRq2ABk3eLoxwZELpH6zhl3FbAoJ7Vm1gofKx6El1Ib5z23NUEhF9AsGl7y+dzLe5Cw2AArGTA==";
      };
    };
    "d3-time-3.1.0" = {
      name = "d3-time";
      packageName = "d3-time";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-time/-/d3-time-3.1.0.tgz";
        sha512 = "VqKjzBLejbSMT4IgbmVgDjpkYrNWUYJnbCGo874u7MMKIWsILRX+OpX/gTk8MqjpT1A/c6HY2dCA77ZN0lkQ2Q==";
      };
    };
    "d3-time-format-4.1.0" = {
      name = "d3-time-format";
      packageName = "d3-time-format";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-time-format/-/d3-time-format-4.1.0.tgz";
        sha512 = "dJxPBlzC7NugB2PDLwo9Q8JiTR3M3e4/XANkreKSUxF8vvXKqm1Yfq4Q5dl8budlunRVlUUaDUgFt7eA8D6NLg==";
      };
    };
    "d3-timer-2.0.0" = {
      name = "d3-timer";
      packageName = "d3-timer";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-timer/-/d3-timer-2.0.0.tgz";
        sha512 = "TO4VLh0/420Y/9dO3+f9abDEFYeCUr2WZRlxJvbp4HPTQcSylXNiL6yZa9FIUvV1yRiFufl1bszTCLDqv9PWNA==";
      };
    };
    "d3-timer-3.0.1" = {
      name = "d3-timer";
      packageName = "d3-timer";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-timer/-/d3-timer-3.0.1.tgz";
        sha512 = "ndfJ/JxxMd3nw31uyKoY2naivF+r29V+Lc0svZxe1JvvIRmi8hUsrMvdOwgS1o6uBHmiz91geQ0ylPP0aj1VUA==";
      };
    };
    "d3-transition-3.0.1" = {
      name = "d3-transition";
      packageName = "d3-transition";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-transition/-/d3-transition-3.0.1.tgz";
        sha512 = "ApKvfjsSR6tg06xrL434C0WydLr7JewBB3V+/39RMHsaXTOG0zmt/OAXeng5M5LBm0ojmxJrpomQVZ1aPvBL4w==";
      };
    };
    "d3-zoom-3.0.0" = {
      name = "d3-zoom";
      packageName = "d3-zoom";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-zoom/-/d3-zoom-3.0.0.tgz";
        sha512 = "b8AmV3kfQaqWAuacbPuNbL6vahnOJflOhexLzMMNLga62+/nh0JzvJ0aO/5a5MVgUFGS7Hu1P9P03o3fJkDCyw==";
      };
    };
    "dayjs-1.10.6" = {
      name = "dayjs";
      packageName = "dayjs";
      version = "1.10.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/dayjs/-/dayjs-1.10.6.tgz";
        sha512 = "AztC/IOW4L1Q41A86phW5Thhcrco3xuAA+YX/BLpLWWjRcTj5TOt/QImBLmCKlrF7u7k47arTnOyL6GnbG8Hvw==";
      };
    };
    "delaunator-5.0.0" = {
      name = "delaunator";
      packageName = "delaunator";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delaunator/-/delaunator-5.0.0.tgz";
        sha512 = "AyLvtyJdbv/U1GkiS6gUUzclRoAY4Gs75qkMygJJhU75LW4DNuSF2RMzpxs9jw9Oz1BobHjTdkG3zdP55VxAqw==";
      };
    };
    "dir-glob-3.0.1" = {
      name = "dir-glob";
      packageName = "dir-glob";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dir-glob/-/dir-glob-3.0.1.tgz";
        sha512 = "WkrWp9GR4KXfKGYzOLmTuGVi1UWFfws377n9cc55/tb6DuqyF6pcQ5AbiHEshaDpY9v6oaSr2XCDidGmMwdzIA==";
      };
    };
    "fast-glob-3.2.7" = {
      name = "fast-glob";
      packageName = "fast-glob";
      version = "3.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-glob/-/fast-glob-3.2.7.tgz";
        sha512 = "rYGMRwip6lUMvYD3BTScMwT1HtAs2d71SMv66Vrxs0IekGZEjhM0pcMfjQPnknBt2zeCwQMEupiN02ZP4DiT1Q==";
      };
    };
    "fastq-1.12.0" = {
      name = "fastq";
      packageName = "fastq";
      version = "1.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastq/-/fastq-1.12.0.tgz";
        sha512 = "VNX0QkHK3RsXVKr9KrlUv/FoTa0NdbYoHHl7uXHv2rzyHSlxjdNAKug2twd9luJxpcyNeAgf5iPPMutJO67Dfg==";
      };
    };
    "fill-range-7.0.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.0.1.tgz";
        sha512 = "qOo9F+dMUmC2Lcb4BbVvnKJxTPjCm+RRpe4gDuGrzkL7mEVl/djYSu2OdQ2Pa302N4oqkSg9ir6jaLWJ2USVpQ==";
      };
    };
    "fs-extra-8.1.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-8.1.0.tgz";
        sha512 = "yhlQgA6mnOJUKOsRUFsgJdQCvkKhcz8tlZG5HBQfReYZy46OwLcY+Zia0mtdHsOo9y/hP+CxMN0TU9QxoOtG4g==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "glob-7.1.7" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.7.tgz";
        sha512 = "OvD9ENzPLbegENnYP5UUfJIirTg4+XwMWGaQfQTY0JenxNvvIKP3U3/tAQSPIu/lHxXYSZmpXlUHeqAIdKzBLQ==";
      };
    };
    "glob-parent-5.1.2" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-5.1.2.tgz";
        sha512 = "AOIgSQCepiJYwP3ARnGx+5VnTu2HBYdzbGP45eLw1vr3zB3vZLeyed1sC9hnbcOc9/SrMyM5RPQrkGz4aS9Zow==";
      };
    };
    "globby-10.0.1" = {
      name = "globby";
      packageName = "globby";
      version = "10.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/globby/-/globby-10.0.1.tgz";
        sha512 = "sSs4inE1FB2YQiymcmTv6NWENryABjUNPeWhOvmn4SjtKybglsyPZxFB3U1/+L1bYi0rNZDqCLlHyLYDl1Pq5A==";
      };
    };
    "graceful-fs-4.2.8" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.8.tgz";
        sha512 = "qkIilPUYcNhJpd33n0GBXTB1MMPp14TxEsEs0pTrsSVucApsYzW5V+Q8Qxhik6KU3evy+qkAAowTByymK0avdg==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "ignore-5.1.8" = {
      name = "ignore";
      packageName = "ignore";
      version = "5.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/ignore/-/ignore-5.1.8.tgz";
        sha512 = "BMpfD7PpiETpBl/A6S498BaIJ6Y/ABT93ETbby2fP00v4EbvPBXWEoaR1UBPKs3iR53pJY7EtZk5KACI57i1Uw==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "internmap-2.0.3" = {
      name = "internmap";
      packageName = "internmap";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/internmap/-/internmap-2.0.3.tgz";
        sha512 = "5Hh7Y1wQbvY5ooGgPbDaL5iYLAPzMTUrjMulskHLH6wnv/A+1q5rgEaiuqEjB+oxGXIVZs1FF+R/KPN3ZSQYYg==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha1 = "a88c02535791f02ed37c76a1b9ea9773c833f8c2";
      };
    };
    "is-glob-4.0.1" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.1.tgz";
        sha512 = "5G0tKtBTFImOqDnLB2hG6Bp2qcKEFduo4tZu9MT/H6NQv/ghhy30o55ufafxJ/LdH79LLs2Kfrn85TLKyA7BUg==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "is-plain-object-3.0.1" = {
      name = "is-plain-object";
      packageName = "is-plain-object";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-object/-/is-plain-object-3.0.1.tgz";
        sha512 = "Xnpx182SBMrr/aBik8y+GuR4U1L9FqMSojwDQwPMmxyC6bvEqly9UBCxhauBF5vNh2gwWJNX6oDV7O+OM4z34g==";
      };
    };
    "jsonfile-4.0.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-4.0.0.tgz";
        sha1 = "8771aae0799b64076b76640fca058f9c10e33ecb";
      };
    };
    "jwt-decode-3.1.2" = {
      name = "jwt-decode";
      packageName = "jwt-decode";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jwt-decode/-/jwt-decode-3.1.2.tgz";
        sha512 = "UfpWE/VZn0iP50d8cz9NrZLM9lSWhcJ+0Gt/nm4by88UL+J1SiKN8/5dkjMmbEzwL2CAe+67GsegCbIKtbp75A==";
      };
    };
    "leaflet-1.7.1" = {
      name = "leaflet";
      packageName = "leaflet";
      version = "1.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/leaflet/-/leaflet-1.7.1.tgz";
        sha512 = "/xwPEBidtg69Q3HlqPdU3DnrXQOvQU/CCHA1tcDQVzOwm91YMYaILjNp7L4Eaw5Z4sOYdbBz6koWyibppd8Zqw==";
      };
    };
    "lit-2.1.1" = {
      name = "lit";
      packageName = "lit";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lit/-/lit-2.1.1.tgz";
        sha512 = "yqDqf36IhXwOxIQSFqCMgpfvDCRdxLCLZl7m/+tO5C9W/OBHUj17qZpiMBT35v97QMVKcKEi1KZ3hZRyTwBNsQ==";
      };
    };
    "lit-element-3.1.1" = {
      name = "lit-element";
      packageName = "lit-element";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lit-element/-/lit-element-3.1.1.tgz";
        sha512 = "14ClnMAU8EXnzC+M2/KDd3SFmNUn1QUw1+GxWkEMwGV3iaH8ObunMlO5svzvaWlkSV0WlxJCi40NGnDVJ2XZKQ==";
      };
    };
    "lit-html-2.1.1" = {
      name = "lit-html";
      packageName = "lit-html";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lit-html/-/lit-html-2.1.1.tgz";
        sha512 = "E4BImK6lopAYanJpvcGaAG8kQFF1ccIulPu2BRNZI7acFB6i4ujjjsnaPVFT1j/4lD9r8GKih0Y8d7/LH8SeyQ==";
      };
    };
    "merge2-1.4.1" = {
      name = "merge2";
      packageName = "merge2";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge2/-/merge2-1.4.1.tgz";
        sha512 = "8q7VEgMJW4J8tcfVPy8g09NcQwZdbwFEqhe/WZkoIzjn/3TGDwtOCYtXGxA3O8tPzpczCCDgv+P2P5y00ZJOOg==";
      };
    };
    "micromatch-4.0.4" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.4.tgz";
        sha512 = "pRmzw/XUcwXGpD9aI9q/0XOwLNygjETJ8y0ao0wdqprrzDa4YnxLcz7fQRZr8voh8V10kGhABbNcHVk5wHgWwg==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-type-4.0.0" = {
      name = "path-type";
      packageName = "path-type";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-type/-/path-type-4.0.0.tgz";
        sha512 = "gDKb8aZMDeD/tZWs9P6+q0J9Mwkdl6xMV8TjnGP3qJVJ06bdMgkbBlLU8IdfOsIsFz2BW1rNVT3XuNEl8zPAvw==";
      };
    };
    "picomatch-2.3.0" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.0.tgz";
        sha512 = "lY1Q/PiJGC2zOv/z391WOTD+Z02bCgsFfvxoXXf6h7kv9o+WmsmzYqrAwY63sNgOxE4xEdq0WyUnXfKeBrSvYw==";
      };
    };
    "pwa-helper-components-0.2.10" = {
      name = "pwa-helper-components";
      packageName = "pwa-helper-components";
      version = "0.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/pwa-helper-components/-/pwa-helper-components-0.2.10.tgz";
        sha512 = "0qxa/mFM4ssqFHNB1ka+MPefBh/lAVp+fAkWTxfqPsLXaKMt1g0PHQ8OVAr4qOWPQqYW4wuUpf6ljD/YQGmlzQ==";
      };
    };
    "pwa-helpers-0.9.1" = {
      name = "pwa-helpers";
      packageName = "pwa-helpers";
      version = "0.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pwa-helpers/-/pwa-helpers-0.9.1.tgz";
        sha512 = "4sP/C9sSxQ3w80AATmvCEI3R+MHzCwr2RSZEbLyMkeJgV3cRk7ySZRUrQnBDSA7A0/z6dkYtjuXlkhN1ZFw3iA==";
      };
    };
    "queue-microtask-1.2.3" = {
      name = "queue-microtask";
      packageName = "queue-microtask";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
        sha512 = "NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
      };
    };
    "reusify-1.0.4" = {
      name = "reusify";
      packageName = "reusify";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/reusify/-/reusify-1.0.4.tgz";
        sha512 = "U9nH88a3fc/ekCF1l0/UP1IosiuIjyTh7hBvXVMHYgVcfGvt897Xguj2UOLDeI5BG2m7/uwyaLVT6fbtCwTyzw==";
      };
    };
    "robust-predicates-3.0.1" = {
      name = "robust-predicates";
      packageName = "robust-predicates";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/robust-predicates/-/robust-predicates-3.0.1.tgz";
        sha512 = "ndEIpszUHiG4HtDsQLeIuMvRsDnn8c8rYStabochtUeCvfuvNptb5TUbVD68LRAILPX7p9nqQGh4xJgn3EHS/g==";
      };
    };
    "rollup-plugin-copy-3.4.0" = {
      name = "rollup-plugin-copy";
      packageName = "rollup-plugin-copy";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup-plugin-copy/-/rollup-plugin-copy-3.4.0.tgz";
        sha512 = "rGUmYYsYsceRJRqLVlE9FivJMxJ7X6jDlP79fmFkL8sJs7VVMSVyA2yfyL+PGyO/vJs4A87hwhgVfz61njI+uQ==";
      };
    };
    "run-parallel-1.2.0" = {
      name = "run-parallel";
      packageName = "run-parallel";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-parallel/-/run-parallel-1.2.0.tgz";
        sha512 = "5l4VyZR86LZ/lDxZTR6jqL8AFE2S0IFLMP26AbjsLVADxHdhB/c0GUsH+y39UfCi3dzz8OlQuPmnaJOMoDHQBA==";
      };
    };
    "rw-1.3.3" = {
      name = "rw";
      packageName = "rw";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/rw/-/rw-1.3.3.tgz";
        sha512 = "PdhdWy89SiZogBLaw42zdeqtRJ//zFd2PgQavcICDUgJT5oW10QCRKbJ6bg4r0/UY2M6BWd5tkxuGFRvCkgfHQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "slash-3.0.0" = {
      name = "slash";
      packageName = "slash";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/slash/-/slash-3.0.0.tgz";
        sha512 = "g9Q1haeby36OSStwb4ntCGGGaKsaVSjQ68fBxoQcutl5fS1vuY18H3wSt3jFyFtrkx+Kz0V1G85A4MyAdDMi2Q==";
      };
    };
    "tippy.js-6.3.7" = {
      name = "tippy.js";
      packageName = "tippy.js";
      version = "6.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/tippy.js/-/tippy.js-6.3.7.tgz";
        sha512 = "E1d3oP2emgJ9dRQZdf3Kkn0qJgI6ZLpyS5z6ZkY1DF3kaQaBsGZsndEpHwx+eC+tYM41HaSNvNtLx8tU57FzTQ==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
    "tslib-2.3.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.3.1.tgz";
        sha512 = "77EbyPPpMz+FRFRuAFlWMtmgUWGe9UOG2Z25NqCwiIjRhOf5iKGuzSe5P2w1laq+FkRy4p+PCuVkJSGkzTEKVw==";
      };
    };
    "universalify-0.1.2" = {
      name = "universalify";
      packageName = "universalify";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-0.1.2.tgz";
        sha512 = "rBJeI5CXAlmy1pV+617WB9J63U6XcazHHF2f2dbJix4XzpUF0RS3Zbj0FGIOCAva5P/d/GBOYaACQ1w+0azUkg==";
      };
    };
    "wicg-inert-3.1.1" = {
      name = "wicg-inert";
      packageName = "wicg-inert";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/wicg-inert/-/wicg-inert-3.1.1.tgz";
        sha512 = "PhBaNh8ur9Xm4Ggy4umelwNIP6pPP1bv3EaWaKqfb/QNme2rdLjm7wIInvV4WhxVHhzA4Spgw9qNSqWtB/ca2A==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
  };
  args = {
    name = "gramps-js";
    packageName = "gramps-js";
    version = "0.22.0";
    src = ./Gramps.js;
    dependencies = [
      sources."@material/animation-14.0.0-canary.53b3cad2f.0"
      sources."@material/base-14.0.0-canary.53b3cad2f.0"
      sources."@material/button-14.0.0-canary.53b3cad2f.0"
      sources."@material/circular-progress-14.0.0-canary.53b3cad2f.0"
      sources."@material/density-14.0.0-canary.53b3cad2f.0"
      sources."@material/dialog-14.0.0-canary.53b3cad2f.0"
      sources."@material/dom-14.0.0-canary.53b3cad2f.0"
      sources."@material/drawer-14.0.0-canary.53b3cad2f.0"
      sources."@material/elevation-14.0.0-canary.53b3cad2f.0"
      sources."@material/feature-targeting-14.0.0-canary.53b3cad2f.0"
      sources."@material/floating-label-14.0.0-canary.53b3cad2f.0"
      sources."@material/focus-ring-14.0.0-canary.53b3cad2f.0"
      sources."@material/form-field-14.0.0-canary.53b3cad2f.0"
      sources."@material/icon-button-14.0.0-canary.53b3cad2f.0"
      sources."@material/line-ripple-14.0.0-canary.53b3cad2f.0"
      sources."@material/linear-progress-14.0.0-canary.53b3cad2f.0"
      sources."@material/list-14.0.0-canary.53b3cad2f.0"
      sources."@material/menu-14.0.0-canary.53b3cad2f.0"
      sources."@material/menu-surface-14.0.0-canary.53b3cad2f.0"
      sources."@material/mwc-base-0.27.0"
      sources."@material/mwc-button-0.27.0"
      sources."@material/mwc-checkbox-0.27.0"
      sources."@material/mwc-circular-progress-0.27.0"
      sources."@material/mwc-dialog-0.27.0"
      sources."@material/mwc-drawer-0.27.0"
      sources."@material/mwc-fab-0.27.0"
      sources."@material/mwc-floating-label-0.27.0"
      sources."@material/mwc-formfield-0.27.0"
      sources."@material/mwc-icon-0.27.0"
      sources."@material/mwc-icon-button-0.27.0"
      sources."@material/mwc-line-ripple-0.27.0"
      sources."@material/mwc-linear-progress-0.27.0"
      sources."@material/mwc-list-0.27.0"
      sources."@material/mwc-menu-0.27.0"
      sources."@material/mwc-notched-outline-0.27.0"
      sources."@material/mwc-radio-0.27.0"
      sources."@material/mwc-ripple-0.27.0"
      sources."@material/mwc-select-0.27.0"
      sources."@material/mwc-slider-0.27.0"
      sources."@material/mwc-snackbar-0.27.0"
      sources."@material/mwc-switch-0.27.0"
      sources."@material/mwc-tab-0.27.0"
      sources."@material/mwc-tab-bar-0.27.0"
      sources."@material/mwc-tab-indicator-0.27.0"
      sources."@material/mwc-tab-scroller-0.27.0"
      sources."@material/mwc-textarea-0.27.0"
      sources."@material/mwc-textfield-0.27.0"
      sources."@material/mwc-top-app-bar-0.27.0"
      sources."@material/notched-outline-14.0.0-canary.53b3cad2f.0"
      sources."@material/progress-indicator-14.0.0-canary.53b3cad2f.0"
      sources."@material/radio-14.0.0-canary.53b3cad2f.0"
      sources."@material/ripple-14.0.0-canary.53b3cad2f.0"
      sources."@material/rtl-14.0.0-canary.53b3cad2f.0"
      sources."@material/select-14.0.0-canary.53b3cad2f.0"
      sources."@material/shape-14.0.0-canary.53b3cad2f.0"
      sources."@material/slider-14.0.0-canary.53b3cad2f.0"
      sources."@material/snackbar-14.0.0-canary.53b3cad2f.0"
      sources."@material/switch-14.0.0-canary.53b3cad2f.0"
      sources."@material/tab-14.0.0-canary.53b3cad2f.0"
      sources."@material/tab-bar-14.0.0-canary.53b3cad2f.0"
      sources."@material/tab-indicator-14.0.0-canary.53b3cad2f.0"
      sources."@material/tab-scroller-14.0.0-canary.53b3cad2f.0"
      sources."@material/textfield-14.0.0-canary.53b3cad2f.0"
      sources."@material/theme-14.0.0-canary.53b3cad2f.0"
      sources."@material/tokens-14.0.0-canary.53b3cad2f.0"
      sources."@material/top-app-bar-14.0.0-canary.53b3cad2f.0"
      sources."@material/touch-target-14.0.0-canary.53b3cad2f.0"
      sources."@material/typography-14.0.0-canary.53b3cad2f.0"
      sources."@mdi/js-5.9.55"
      sources."@nodelib/fs.scandir-2.1.5"
      sources."@nodelib/fs.stat-2.0.5"
      sources."@nodelib/fs.walk-1.2.8"
      sources."@popperjs/core-2.11.7"
      sources."@types/fs-extra-8.1.2"
      sources."@types/geojson-7946.0.8"
      sources."@types/glob-7.1.4"
      sources."@types/leaflet-1.7.5"
      sources."@types/minimatch-3.0.5"
      sources."@types/node-16.7.6"
      sources."@types/trusted-types-2.0.2"
      sources."array-union-2.1.0"
      sources."balanced-match-1.0.2"
      sources."blocking-elements-0.1.1"
      sources."brace-expansion-1.1.11"
      sources."braces-3.0.2"
      sources."colorette-1.3.0"
      sources."concat-map-0.0.1"
      (sources."d3-7.8.2" // {
        dependencies = [
          sources."d3-color-3.1.0"
          sources."d3-dispatch-3.0.1"
          sources."d3-drag-3.0.0"
          sources."d3-ease-3.0.1"
          sources."d3-format-3.1.0"
          sources."d3-interpolate-3.0.1"
          sources."d3-path-3.1.0"
          sources."d3-timer-3.0.1"
          sources."d3-transition-3.0.1"
          sources."d3-zoom-3.0.0"
        ];
      })
      sources."d3-array-3.2.2"
      sources."d3-axis-3.0.0"
      (sources."d3-brush-3.0.0" // {
        dependencies = [
          sources."d3-transition-3.0.1"
        ];
      })
      sources."d3-chord-3.0.1"
      sources."d3-color-2.0.0"
      sources."d3-contour-4.0.2"
      sources."d3-delaunay-6.0.2"
      sources."d3-dispatch-2.0.0"
      (sources."d3-drag-2.0.0" // {
        dependencies = [
          sources."d3-selection-2.0.0"
        ];
      })
      (sources."d3-dsv-3.0.1" // {
        dependencies = [
          sources."commander-7.2.0"
          sources."iconv-lite-0.6.3"
        ];
      })
      sources."d3-ease-2.0.0"
      sources."d3-fetch-3.0.1"
      sources."d3-force-3.0.0"
      sources."d3-format-2.0.0"
      sources."d3-geo-3.1.0"
      sources."d3-hierarchy-3.1.2"
      sources."d3-interpolate-2.0.1"
      sources."d3-path-2.0.0"
      sources."d3-polygon-3.0.1"
      sources."d3-quadtree-3.0.1"
      sources."d3-random-3.0.1"
      sources."d3-scale-4.0.2"
      sources."d3-scale-chromatic-3.0.0"
      sources."d3-selection-3.0.0"
      (sources."d3-shape-3.2.0" // {
        dependencies = [
          sources."d3-path-3.1.0"
        ];
      })
      sources."d3-time-3.1.0"
      sources."d3-time-format-4.1.0"
      sources."d3-timer-2.0.0"
      sources."dayjs-1.10.6"
      sources."delaunator-5.0.0"
      sources."dir-glob-3.0.1"
      sources."fast-glob-3.2.7"
      sources."fastq-1.12.0"
      sources."fill-range-7.0.1"
      sources."fs-extra-8.1.0"
      sources."fs.realpath-1.0.0"
      sources."glob-7.1.7"
      sources."glob-parent-5.1.2"
      sources."graceful-fs-4.2.8"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."internmap-2.0.3"
      sources."is-extglob-2.1.1"
      sources."is-glob-4.0.1"
      sources."is-number-7.0.0"
      sources."is-plain-object-3.0.1"
      sources."jsonfile-4.0.0"
      sources."jwt-decode-3.1.2"
      sources."leaflet-1.7.1"
      (sources."lit-2.1.1" // {
        dependencies = [
          sources."@lit/reactive-element-1.1.1"
          sources."lit-element-3.1.1"
          sources."lit-html-2.1.1"
        ];
      })
      sources."merge2-1.4.1"
      sources."micromatch-4.0.4"
      sources."minimatch-3.0.4"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."path-type-4.0.0"
      sources."picomatch-2.3.0"
      sources."pwa-helper-components-0.2.10"
      sources."pwa-helpers-0.9.1"
      sources."queue-microtask-1.2.3"
      sources."reusify-1.0.4"
      sources."robust-predicates-3.0.1"
      (sources."rollup-plugin-copy-3.4.0" // {
        dependencies = [
          sources."globby-10.0.1"
          sources."ignore-5.1.8"
        ];
      })
      sources."run-parallel-1.2.0"
      sources."rw-1.3.3"
      sources."safer-buffer-2.1.2"
      sources."slash-3.0.0"
      sources."tippy.js-6.3.7"
      sources."to-regex-range-5.0.1"
      sources."tslib-2.3.1"
      sources."universalify-0.1.2"
      sources."wicg-inert-3.1.1"
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The frontend for the Gramps Web genealogical research system.";
      license = "AGPL";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
