#!/usr/bin/env bash

if [[ "$1" == "update" ]]; then
    pushd $FLAKE/../falcon || exit
    nix flake lock --update-input nixpkgs
    nix flake lock --update-input home-manager
    nix flake lock --update-input nixos-hardware
    popd || exit
fi

rsync -rvhtz ~/code/mynixos/ falcon:code/mynixos/
# rsync -rvhtz ~/code/jules/ falcon:code/jules/ --exclude data --exclude webdata/.scrapy/httpcache --exclude webdata/data

# ssh falcon -t zsh -ci "sd\ nixos\ build" 
et falcon