#!/usr/bin/env bash

if [[ "$1" == "update" ]]; then
    pushd $FLAKE/../falcon || exit
    nix flake lock --update-input nixpkgs
    nix flake lock --update-input home-manager
    nix flake lock --update-input nixos-hardware
    popd || exit
fi

rsync -rvhtz ~/Nextcloud/code/mynixos/ falcon:Nextcloud/code/mynixos/
# rsync -rvhtz ~/code/jules/ falcon:code/jules/ --exclude data --exclude webdata/.scrapy/httpcache --exclude webdata/data

args=("$@")
# remove update from args if it exists
args=("${args[@]/update}")

buildarg="boot"
if [[ " ${args[*]} " == *" switch "* ]]; then
    buildarg="switch"
fi

# et falcon
ssh falcon <<EOF
source ~/.zshrc
if [ -z "$(ls -A ~/sd)" ]; then
    sudo mount --bind ~/Nextcloud/code/mynixos/dotfiles/sd ~/sd
fi
sd nixos rebuild $buildarg
EOF