#!/usr/bin/env bash


# et falcon
ssh falcon <<EOF
# /usr/bin/env bash
# source ~/.zshrc
# if [ -z "$(ls -A ~/sd)" ]; then
#     sudo mount --bind ~/Nextcloud/code/mynixos/dotfiles/sd ~/sd
# fi]
# sd nixos rebuild $buildarg

rebuildswitch
EOF