# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ pkgs, modulesPath, inputs, ... }: {

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    (inputs.nixos-hardware.nixosModules.dell-xps-13-9360)
  ];

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "21.05"; # Did you read the comment?

  boot.kernelPackages = pkgs.linuxPackages_latest;

  boot.initrd.systemd.enable = true;
  boot.initrd.availableKernelModules =
    [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [ "video=eDP-1:d" ]; # Disable the internal display
  boot.extraModulePackages = [ ];
  # boot.kernelParams = [ "intel_pstate=disable" ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/8b21b7fa-e15a-45af-b718-da23df216fc4";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4056-2596";
    fsType = "vfat";
  };

  swapDevices = [ ];

  #  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  #  services.tlp.settings = { USB_AUTOSUSPEND = 0; };

  services.xserver.videoDrivers = [ "intel" ];
  hardware.cpu.intel.updateMicrocode = true;
  # For 32 bit applications
  #  hardware.opengl.driSupport32Bit = true;

  nixpkgs.config.packageOverrides = pkgs: {
    intel-vaapi-driver = pkgs.intel-vaapi-driver.override { enableHybridCodec = true; };
  };
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver # LIBVA_DRIVER_NAME=iHD
      # vaapiIntel # LIBVA_DRIVER_NAME=i965 (older but works better for Firefox/Chromium)
      intel-vaapi-driver
      libvdpau-va-gl
    ];
  };

  # networking.interfaces.wlp58s0.useDHCP = true;

}
