hs.hotkey.bind({"alt"}, "e", function()
                  hs.execute("open -n -a Finder")
                end)
                hs.hotkey.bind({"alt"}, "f", function()
                  hs.execute("open -n -a Firefox")
                end)
                hs.hotkey.bind({"alt"}, "t", function()
                  hs.execute("open -n -a Terminal")
                end)