#!/usr/bin/env bash

LEOPARD=~/Nextcloud/code/mynixos/machines/leopard

# Original sync and build logic
if [[ " $* " == *" update "* ]]; then
    # Pin current nixpkgs before updating
    CURRENT_NIXPKGS_REV=$(jq -r '.nodes.nixpkgs.locked.rev' "$LEOPARD/flake.lock" 2>/dev/null)
    if [[ -n "$CURRENT_NIXPKGS_REV" && "$CURRENT_NIXPKGS_REV" != "null" ]]; then
        echo "Pinning current nixpkgs ($CURRENT_NIXPKGS_REV) to nixpkgs_pin..."
        sed -i '' "s|nixpkgs_pin.url = \"github:nixos/nixpkgs/[a-f0-9]*\";|nixpkgs_pin.url = \"github:nixos/nixpkgs/$CURRENT_NIXPKGS_REV\";|" "$LEOPARD/flake.nix"
    fi

    pushd $LEOPARD || exit
    nix flake update
    # nix flake lock --update-input home-manager
    # nix flake lock --update-input nixos-hardware
    popd || exit
# else
#     pushd ~/Nextcloud/code/mynixos/machines/leopard || exit
#     nix flake lock --update-input mynixosp
#     popd || exit
fi

rsync -rvhtz ~/Nextcloud/code/mynixos/ leopard:Nextcloud/code/mynixos/
# rsync -rvhtz ~/code/jules/ falcon:code/jules/ --exclude data --exclude webdata/.scrapy/httpcache --exclude webdata/data

args=("$@")
# remove update from args if it exists
args=("${args[@]/update}")

buildarg="boot"
if [[ " ${args[*]} " == *" switch "* ]]; then
    buildarg="switch"
fi

if [[ " $* " == *" build "* ]]; then

    echo "Building"

    ssh -t leopard "sudo nixos-rebuild switch --impure --flake \$FLAKE 2>&1 | cat"

fi


# et leopard
# ssh falcon <<EOF
# /usr/bin/env bash
# # source ~/.zshrc
# # if [ -z "$(ls -A ~/sd)" ]; then
# #     sudo mount --bind ~/Nextcloud/code/mynixos/dotfiles/sd ~/sd
# # fi
# # sd nixos rebuild $buildarg
# rebuildswitch
# EOF
