#!/usr/bin/env bash

pushd $FLAKE/rpi4 || exit
colmena apply --on rpi4
popd || exit

if [[ $1 == "reboot" ]]; then
    echo "Rebooting rpi4"
    ssh rpi4 sudo reboot
fi

if [[ $1 == "shell" ]]; then
    et rpi4
fi