#!/usr/bin/env bash

sshqfunc() { echo "bash -c $(printf "%q" "$(declare -f "$@"); $1 \"\$@\"")"; };

work() {
   cd /data/movies
   wget -O "" $1
}

# ssh rpi4 "$(sshqfunc work)" -- "$(printf "%q" "$1")"
ssh 192.168.178.50 "$(sshqfunc work)" -- "$1"