#!/usr/bin/env bash

file_ending="$1"
if [ -z "$file_ending" ]; then
    echo "No file ending given"
    exit 1
fi

folder=$(pwd)
echo "Processing current folder: $folder"

for file in "$folder"/*.${file_ending}
do
    echo "Processing $file"
    # cp1251 is the encoding of the files in windows
    convmv --notest -r -f cp1251 -t utf-8 "$file"
done