#!/usr/bin/env bash

sshfs falcon:/data2/stash ~/Downloads/stash/

trap 'umount ~/Downloads/stash; exit' SIGINT

# Keep the script running until interrupted
echo "Press Ctrl+C to unmount and exit..."
while true; do
    sleep 1
done

umount ~/Downloads/stash