#!/usr/bin/env bash

sudo echo "Updating mac"

pushd $FLAKE || exit

nix flake update

rebuildswitch

number=$(($(readlink /nix/var/nix/profiles/system | sed 's/system-\([0-9]*\)-link/\1/') - 1 ))

nvd diff "/nix/var/nix/profiles/system-$number-link" /run/current-system

popd || exit
