#!/usr/bin/env bash
set -euo pipefail

sudo echo "Updating mac"

pushd $FLAKE || exit

nix flake update

# rebuildswitch:
sudo sh -c 'set -o pipefail; ulimit -n 1048576; darwin-rebuild switch --flake ./ --impure 2>&1 | nom'

number=$(($(readlink /nix/var/nix/profiles/system | sed 's/system-\([0-9]*\)-link/\1/') - 1 ))

nvd diff "/nix/var/nix/profiles/system-$number-link" /run/current-system

popd || exit
