#!/usr/bin/env bash

pushd $FLAKE || exit

nixos-rebuild --impure build --flake ./ |&nom

if [[ "${PIPESTATUS[0]}" != "0"  ]]; then
    echo "Build failed!"
    exit 1
fi

nvd diff /run/current-system result

read -n 1 -p "any key to continue or Ctrl-c to aboard" input

if [[ "$2" == "gc" ]]; then
    echo "collecting garbage"
    sd nixos gc
fi

sudo nixos-rebuild --impure "$1" --flake ./

changelog_file="./update_changelog.txt"

{
    echo "Update on $(date)";
    echo "";
    nvd diff /run/current-system result;
    echo "-------------------------------------------------";
    echo "";
    if [[ -f $changelog_file ]]; then
        cat $changelog_file;
    fi;
} > tmp.txt && mv tmp.txt $changelog_file


# check if result folder symlink exists
if [[ -L result ]]; then
    rm ./result
fi

echo "Update complete. Reboot to apply changes."

popd || exit