#!/usr/bin/env bash

current=$(sudo nix-env --list-generations --profile /nix/var/nix/profiles/system | grep '(current)' | awk '{print $1}')

$(sudo nixos-rebuild switch --impure --flake $FLAKE |& nom) && \
nvd diff /run/current-system /nix/var/nix/profiles/system-$current-link
