#!/usr/bin/env bash

pushd $FLAKE || exit

EPOCH=$(cat ./flake.lock | jq -r '.nodes.nixpkgs.locked.lastModified')
NIXPKGS_DATE=$(date -d "1970-01-01 UTC $EPOCH seconds" +"%Y-%m-%d")

latest_seconds=$(date --date "1 days ago" +'%s')

if [[ $EPOCH -lt $latest_seconds ]]; then

    echo "Last update was on $NIXPKGS_DATE. Updating now."

    fwupdmgr refresh
    fwupdmgr get-updates
    fwupdmgr update

    nix flake update
else
    echo "Flake inputs already updated. Skipping re-download."
fi

nixos-rebuild build --flake ./ |&nom

if [[ "${PIPESTATUS[0]}" != "0"  ]]; then
    echo "Build failed!"
    exit 1
fi

nvd diff /run/current-system result

read -n 1 -p "any key to continue or Ctrl-c to aboard" input

if [[ "$1" == "gc" ]]; then
    echo "collecting garbage"
    sudo nix-collect-garbage -d
fi

sudo nixos-rebuild boot --flake ./

# check if result folder symlink exists
if [[ -L result ]]; then
    rm ./result
fi

popd || exit