#!/usr/bin/env bash
#
# delete config files that are in the way of home manager dotfiles
#
rm ~/.config/gtkrc-2.0
rm ~/.config/katevirc
rm ~/.config/katerc
rm ~/.config/systemsettingsrc
rm ~/.config/kateschemarc
rm ~/.config/kconf_updaterc
rm ~/.config/plasma-localerc
rm ~/.config/ktimezonedrc
rm ~/.config/kxkbrc
rm ~/.config/plasma-org.kde.plasma.desktop-appletsrc
rm ~/.config/kdeglobals
rm ~/.config/powermanagementprofilesrc
rm ~/.config/plasmashellrc
rm ~/.config/kglobalshortcutsrc
rm ~/.config/kded5rc
rm ~/.local/share/krunnerstaterc
rm ~/.config/kwinrc
rm ~/.config/akregatorrc
rm ~/.config/khotkeysrc
rm ~/.config/spectaclerc
rm ~/.config/gtkrc
rm ~/.config/baloofilerc
rm ~/.config/kactivitymanagerd-statsrc
rm ~/.config/user-dirs.locale
rm ~/.config/konsolerc
rm ~/.config/kmixrc
rm ~/.config/kwinrulesrc
rm ~/.config/user-dirs.dirs
rm ~/.config/ksmserverrc
rm ~/.config/kcminputrc
rm ~/.config/startkderc
rm ~/.config/dolphinrc

rm ~/.local/share/user-places.xbel.tbcache
rm ~/.local/share/user-places.xbel