#!/usr/bin/env bash

folder="$1"

cd "$folder"
rm ./*.{xmp,JPG,dng,tif,jpg}
cd ..

immich  upload --recursive "$folder" --album-name "$folder"

# path="$(pwd)/$folder"

# echo $path

# rsync -rht $folder /data/