#!/usr/bin/env bash

# Set up trap to handle Ctrl+C
trap 'echo -e "\nBackup interrupted by user. Exiting..."; exit 1' INT

files=(
    ~/.ssh
    ~/.mozilla
    ~/.vscode
    ~/.cursor
    ~/.gnugpg
    ~/.config # xdg_config_home
    ~/.cache # xdg_cache_home
    ~/.local/share # xdg_data_home
    ~/.local/state # user_state
    # ~/.local/bin # user_bin
    # ~/.local/var # user_var
)

for file in "${files[@]}"; do
    if [ -d "$file" ]; then
        echo "Backing up $file"
        size=$(du -sh "$file" | awk '{print $1}')
        echo "Size: $size"
        rsync -az --delete --stats --info=progress2 --numeric-ids --rsync-path="sudo rsync" "$file" falcon:~/backup/dotfiles/system/
    fi
done


rsync -az --stats --info=progress2 --numeric-ids --rsync-path="sudo rsync" ~/Games/Cyberpunk2077/ falcon:/data3/Games/Cyberpunk2077/