#!/usr/bin/env bash

yt-dlp --cookies ~/Nextcloud/code/mynixos/secrets/gitcrypt/yt-music-cookies.txt \
  -x --audio-format best --audio-quality 0 \
  -o "%(playlist_title)s/%(title)s.%(ext)s" \
  --embed-metadata --embed-thumbnail --convert-thumbnails jpg \
  --ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" \
"https://music.youtube.com/playlist?list=PL2OG5ic9bcj7BlQai1JGTsT7YHpswjwOJ"

