#!/usr/bin/env bash

handlr set .png feh.desktop
handlr set .jpeg feh.desktop
handlr set .jpg feh.desktop
handlr set .torrent transmission-gtk.desktop
handlr set text/html firefox.desktop
handlr set x-scheme-handler/http firefox.desktop
handlr set x-scheme-handler/https firefox.desktop
handlr set x-scheme-handler/about firefox.desktop
handlr set x-scheme-handler/unknown firefox.desktop