# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    #    "${
    #      builtins.fetchGit { url = "https://github.com/NixOS/nixos-hardware.git"; }
    #    }/dell/xps/13-9360"
    #
    #    "${
    #      builtins.fetchGit { url = "https://github.com/NixOS/nixos-hardware.git"; }
    #    }/common/pc/ssd"
  ];

  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.initrd.availableKernelModules =
    [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/8b21b7fa-e15a-45af-b718-da23df216fc4";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4056-2596";
    fsType = "vfat";
  };

  swapDevices = [ ];

  #  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  #  services.tlp.settings = { USB_AUTOSUSPEND = 0; };

  services.xserver.videoDrivers = [ "intel" ];
  hardware.cpu.intel.updateMicrocode = true;
  hardware.opengl.driSupport = true;
  # For 32 bit applications
  #  hardware.opengl.driSupport32Bit = true;

  hardware.opengl = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver # LIBVA_DRIVER_NAME=iHD
      vaapiIntel # LIBVA_DRIVER_NAME=i965 (older but works better for Firefox/Chromium)
    ];
  };

  networking.interfaces.wlp58s0.useDHCP = true;

}
