# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    "${
      builtins.fetchGit { url = "https://github.com/NixOS/nixos-hardware.git"; }
    }/dell/xps/13-9360"

    "${
      builtins.fetchGit { url = "https://github.com/NixOS/nixos-hardware.git"; }
    }/common/pc/ssd"
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/73ccb115-5243-445c-8d3e-5b194fb48428";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B291-CDF1";
    fsType = "vfat";
  };

  swapDevices = [ ];

  #  services.tlp.settings = { USB_AUTOSUSPEND = 0; };

  services.xserver.videoDrivers = [ "intel" ];
  #  hardware.cpu.amd.updateMicrocode = true;
  #  hardware.opengl.driSupport = true;
  # For 32 bit applications
  #  hardware.opengl.driSupport32Bit = true;

  hardware.opengl = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver # LIBVA_DRIVER_NAME=iHD
      vaapiIntel # LIBVA_DRIVER_NAME=i965 (older but works better for Firefox/Chromium)
    ];
  };

  #  networking.interfaces.wlp1s0.useDHCP = true;

}
