hs.hotkey.bind({"cmd"}, "e", function()
  hs.execute("open -a Finder")
end)
hs.hotkey.bind({"cmd"}, "b", function()
  hs.execute("open -n -a Firefox")
end)
hs.hotkey.bind({"cmd"}, "return", function()
  hs.execute("open -n -a Terminal")
end)